ignores and git overrides

diff --git a/zsh/git b/zsh/git
--- a/zsh/git
+++ b/zsh/git
@@ -1,3 +1,48 @@
+function git_commit() {
+  command git commit "$@"
+  exit_status=$?
+  if [ $exit_status -eq 0 ]; then
+    echo "Commit successful! Running additional tasks..."
+    open raycast://extensions/raycast/raycast/confetti
+    ascii-commit-graph --full-width --show-todos --show-issues
+  else
+    echo "Commit failed! Running error handling tasks..."
+  fi
+  return $exit_status
+}
+
+function git_push() {
+  command git push "$@"
+  exit_status=$?
+  if [ $exit_status -eq 0 ]; then
+    echo "Push successful! Running additional tasks..."
+    open raycast://extensions/raycast/raycast/confetti
+    ascii-commit-graph --full-width --show-todos --show-issues
+  else
+    echo "Push failed! Running error handling tasks..."
+  fi
+  return $exit_status
+}
+
+function git_() {
+  subcommand=$1
+  shift  # Remove the subcommand from the arguments
+
+  case "$subcommand" in
+    commit)
+      git_commit "$@"
+      ;;
+    push)
+      git_push "$@"
+      ;;
+    *)
+      command git "$subcommand" "$@"
+      ;;
+  esac
+}
+
+alias git='noglob git_'
+
 function git_commit_push() {
   # if not $1 then use --allow-empty-message argument
   # if no changes then add --allow-empty argument
@@ -13,7 +58,8 @@ function git_commit_push() {
     git push
   fi
 
-  ascii-image-converter ~/.config/check-it-out.gif -Ccf
+  open raycast://extensions/raycast/raycast/confetti
+  ascii-commit-graph --full-width --show-todos --show-issues
 }
 
 alias gitcp=git_commit_push
